version: "3.8"

services:
    django:
        build: .
        container_name: djangoContainer
        command: python manage.py runserver 0.0.0.0:8000
        volumes: 
            - .:/usr/src/app
        ports:
            - "8000:8000"
        depends_on:
            - pgdb
    pgdb:
        image: postgres
        container_name: postgresContainer
        environment: 
            - POSTGRES_DB=postgres
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres

    